# Generated by Django 4.1.5 on 2023-01-18 21:56

import ads.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_selections'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_published',
            field=models.BooleanField(validators=[ads.validators.not_in_status_validator]),
        ),
    ]
