# Generated by Django 4.1.5 on 2023-01-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.ManyToManyField(to='authentications.location'),
        ),
    ]
